- hosts: localhost
  vars:
    source_key: "./.ssh/id_github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_github"
  tasks:
    - import_tasks:
        file: tasks/mac/test.yml
    # - import_tasks:
    #     file: tasks/mac/brew.yml
