
- name: Required libraries for Docker 
  become: true
  apt:
    name: ["curl", "apt-transport-https"]
  tags:
    - docker
    - install

- name: Docker keyring download
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg 
    dest: /usr/share/keyrings/docker-keyring.gpg
  tags:
    - docker
    - install

- name: Docker PPA setting
  become: true
  shell:  echo 'deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME")" stable' | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - docker 
    - install

# - name: Brave Browser PPA setting
#   apt_repository:
#     repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
#     filename: brave-browser-release
#   tags:
#     - brave
#     - install

- name: Docker apt installation
  become: true
  apt:
    update_cache: yes
    name: ["docker-ce","docker-ce-cli","containerd.io","docker-buildx-plugin","docker-compose-plugin"]
  tags:
    - docker 
    - install
