- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  git:
    repo: "git@github.com:mihaimariusbaciu/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/src/.dotfiles"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  become: no
  shell: cd $HOME/.local/src/.dotfiles && ./install_dotfiles
  tags:
    - install
    - dotfiles
    - stow
