- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  git:
    repo: "git@github.com:mihaimariusbaciu/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/src/.dotfiles"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell:
    cmd: bash ./install_dotfiles 
    chdir: "{{ lookup('env', 'HOME') }}/.local/src/.dotfiles" 
  tags:
    - install
    - dotfiles 
    - stow

- name: Nvim Install Plugins
  shell:
    cmd: nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags:
    - install
    - dotfiles
    - nvim



