- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  debugger: always
  ansible.builtin.git:
    repo: "git@github.com:mihaimariusbaciu/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.local/src/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.local/src/.dotfiles && ./install_dotfiles
  tags:
    - install
    - dotfiles
    - stow
