- name: Download obsidian
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.3.4/obsidian_1.3.4_amd64.deb
    dest: /tmp/obsidian.deb
  tags:
    - install
    - obsidian

- name: Remove Any previous obsidians
  become: true
  apt:
    name: obsidian
    state: absent
  tags:
    - install
    - obsidian

- name: Install obsidian .deb package
  become: true
  apt:
    deb: /tmp/obsidian.deb
  tags:
    - install
    - obsidian

